INSERT INTO news (title, text)
VALUES ('COVID-19 vaccination campaign started',
        'The nationwide vaccination campaign against COVID-19 has begun today.'),
       ('New research shows benefits of meditation',
        'A new study conducted by researchers at Harvard Medical School suggests that daily meditation can help lower blood pressure and reduce symptoms of anxiety.'),
       ('Scientists discover new species of lizard',
        'A team of biologists has discovered a new species of lizard in the Amazon rainforest.'),
       ('Apple unveils new iPhone models',
        'Apple has announced the release of three new iPhone models, the iPhone 13, 13 Mini, and 13 Pro.'),
       ('SpaceX launches Falcon 9 rocket',
        'SpaceX has successfully launched a Falcon 9 rocket carrying a satellite into orbit.'),
       ('New study links high sugar intake to heart disease',
        'A new study published in the Journal of the American Medical Association has found a link between high sugar intake and an increased risk of heart disease.'),
       ('Google announces new privacy features',
        'Google has announced new privacy features for its users, including the ability to automatically delete search and location data.'),
       ('Paris Fashion Week kicks off',
        'The bi-annual Paris Fashion Week has begun, showcasing the latest designs from some of the world''s top fashion houses.'),
       ('Tesla introduces new self-driving technology',
        'Tesla has introduced a new self-driving technology that it claims will make driving safer and more convenient.'),
       ('World''s largest solar farm opens in China',
        'China has opened the world''s largest solar farm, which is capable of powering 15,000 homes.');

INSERT INTO comments (username, text, news_id)
VALUES ('JohnDoe', 'Great news! Finally, some hope in these tough times.', 1),
       ('JaneSmith', 'I''m skeptical about the vaccine. Has it been tested enough?', 1),
       ('BobJohnson', 'This is really interesting. I might try meditation myself.', 2),
       ('AliceGreen', 'I''ve always been fascinated by lizards. Can''t wait to learn more about this new species!', 3),
       ('SamWilliams',
        'I''m not really impressed by the new iPhone models. I think I''ll stick with my current phone for now.', 4),
       ('EmilyBrown', 'SpaceX is doing some really amazing things. Can''t wait to see what they come up with next!', 5),
       ('TomWilson', 'This is really concerning. I''ll definitely be cutting back on my sugar intake from now on.', 6),
       ('LucyJones', 'It''s good to see that tech companies are starting to take privacy more seriously.', 7),
       ('DavidLee', 'I always look forward to Paris Fashion Week. So much creativity and talent!', 8),
       ('KarenMiller', 'Self-driving cars are the future. Can''t wait to see how this technology develops!', 9),
       ('MarkTaylor', 'This is great news for the environment. We need more renewable energy sources like this.', 10);