server:
  port: 9000

spring:
  application:
    name: auth-sever
  liquibase:
    enabled: true
jwt:
  privateKey: classpath:certs/private.pem
  publicKey: classpath:certs/public.pem
  expiration: 60